### PR TITLE
[External][SOLLVE V&V] add Fortran test cases

### PR DESCRIPTION
**Pull request by yuanfang-chen**
(it's hard to properly create stacked PR. I meant to commit #34 first, then this one)

### CODE REVIEW

**Comment by ajarmusch** [comment]
this formating - is this from a formatter?

**Comment by yuanfang-chen** [comment]
Only the last commit matters. The first two commits are from https://github.com/llvm/llvm-test-suite/pull/34

**Comment by ajarmusch** [comment]
Have you run lit with these fortran tests? Do they passing?

**Comment by yuanfang-chen** [comment]
I expect many of them to fail. So these are gated by `TEST_SUITE_FORCE_ALL`.

**Pull request closed without merging**
