### PR TITLE
[flang] Enable tests that have structure constructors with allocatable component

### PR DESCRIPTION
**Pull request by kkwli**

### CODE REVIEW

**Review by jeanPerier — APPROVED** [review]
Thank you for the update, the list looks good to me and the test-suite passed for me.

**Review by tarunprabhu — APPROVED** [review]
LGTM. Thanks for the update.

**Comment by kkwli** [comment]
Thanks for the review.

**Comment by DavidSpickett** [comment]
I had to disable 1 of these https://github.com/llvm/llvm-test-suite/commit/44df7fad159a27c7c5339797276460866a1c53d0.

Maybe @luporl will know what the proper fix there is?

**Comment by luporl** [comment]
I would actually be surprised if this test passes on other architectures.

IIUC, both `-fstrict-aliasing` and `-fschedule-insns` flags are not supported by flang:
https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Driver/Options.td#L3687
https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Driver/Options.td#L6177

**Comment by luporl** [comment]
https://github.com/llvm/llvm-test-suite/pull/77 fixes the issue and re-enables pr43808 test.

**Comment by kkwli** [comment]
Thanks @DavidSpickett and @lupori

**Pull request merged**
