### PR TITLE
[UnitTests/Float] Fix makefile in MultiSource/UnitTests/Float

### PR DESCRIPTION
**Pull request by IamYJLee**
```
2024-04-05 01:59:00: running: "make" "-k" "TARGET_CC=None" "TARGET_CXX=None" "TARGET_LLVMGCC=/Users/nshc-yjlee_m/Library/Developer/LxShield/Xcode151_Test_15.1_1.15.1/bin/clang" "TARGET_LLVMGXX=/Users/nshc-yjlee_m/Library/Developer/LxShield/Xcode151_Test_15.1_1.15.1/bin/clang++" "TARGET_FLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "ENABLE_OPTIMIZED=1" "OPTFLAGS=-Os" "LLI_OPTFLAGS=-O2" "LLC_OPTFLAGS=-O2" "DISABLE_JIT=1" "ENABLE_PARALLEL_REPORT=1" "ENABLE_HASHED_PROGRAM_OUTPUT=1" "USE_REFERENCE_OUTPUT=1" "TEST=simple" "CC_UNDER_TEST_IS_CLANG=1" "CC_UNDER_TEST_TARGET_IS_ARM64=1" "ARCH=AArch64" "-C" "MultiSource/UnitTests/Float/" "-j" "16" "report" "report.simple.csv"
Makefile:9: *** invalid syntax in conditional.  Stop.
```
The error occurred and I fixed it.

### CODE REVIEW

**Comment by IamYJLee** [comment]
image

I came across that error and after some debugging, I found out that there was a problem with the Makefile.

**Comment by IamYJLee** [comment]
@spavloff Could you please review what I've found?

**Comment by spavloff** [comment]
LGTM.

Thank you for fixing that!

**Comment by IamYJLee** [comment]
@spavloff Thank you for the review. What else do I need to do to merge?

**Review by spavloff — APPROVED** [review]

**Comment by spavloff** [comment]
You can press the button "Squash and merge".

**Comment by IamYJLee** [comment]
@spavloff I seem to be having trouble locating the "Squash and merge" button. Could you please assist me with finding it?

**Comment by spavloff** [comment]
Do you see such box:
image

**Comment by IamYJLee** [comment]
I cannot find "Squash and merge" box.
스크린샷 2024-04-15 오후 3 08 57

**Comment by IamYJLee** [comment]
@spavloff Thank you so much for your help.

**Pull request merged**
