### PR TITLE
[flang]enable execute_command_line tests

### PR DESCRIPTION
**Pull request by yi-wu-arm**
build and pass all three tests on Linux, will test it on Windows later today

### CODE REVIEW

**Review by tblah — APPROVED** [review]
LGTM: execute command line was added in https://github.com/llvm/llvm-project/pull/74077

**Comment by yi-wu-arm** [comment]
It will compile and run on Windows, but it does not behave the same. This is because Windows has different command, dir <=> ls, timeout <=> sleep.

**Review by tarunprabhu — APPROVED** [review]
Tested on Linux on x86 and it looks to be fine. Thanks for enabling these.

**Comment by tarunprabhu** [comment]
> It will compile and run on Windows, but it does not behave the same. This is because Windows has different command, dir <=> ls, timeout <=> sleep.

Just out of curiosity. What do you mean by this?

**Comment by yi-wu-arm** [comment]
> > It will compile and run on Windows, but it does not behave the same. This is because Windows has different command, dir <=> ls, timeout <=> sleep.
> 
> Just out of curiosity. What do you mean by this?

This is because `execute_command_line` calls `std::system`, and on Windows that is cmd. cmd doesn't have `ls`, the Windows equivalent command is `dir`, and for `timeout` for `sleep`. It will compile and run correct based on the standard, however, the printout from the execution won't be the same on Linux.

**Pull request merged**
