### PR TITLE
[External][SOLLVE V&V] Adding AMD whitelist

### PR DESCRIPTION
**Pull request by AaronLiu20**
adding the AMD whitelist using MI-200 gpus with rocm5.6.0 and clang 18,  created sections for the tests that fail at compile time, runtime, and tests that take more than a minute to run

### CODE REVIEW

**Review by ajarmusch — APPROVED** [review]
LG

**Comment by yuanfang-chen** [comment]
Is the `SYSTEM_GPU` a user-facing option? If so, please mention it in the README file.

**Comment by yuanfang-chen** [comment]
Could you please document `SYSTEM_CPU` in the README?

**Comment by ajarmusch** [comment]
Yes we can

**Pull request merged**
